engines:
  stylelint:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  fixme:
    enabled: true
ratings:
  paths:
    - "db/**/*"
    - "oauth/**/*"
    - "routers/**/*"
    - "utils/**/*"
    - "scripts/**/*"
    - "views/**/*"
exclude_paths:
 - "docs/**/*"
 - "**/jquery*"
 - "**/bootstrap*"
